### ISSUE TITLE
Do blog post announcing User Researcher hire

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#171]
Part of the strategy identified in https://github.com/freelawproject/fundraising/issues/172 is to write blog posts that can attract people to the project. It's a four-party problem (FLP, funder, researcher, and courts). We now have three out of the four ingredients and we need the fourth.

The first blog post announced the project, and now it's time to announce we've got our hire. 

@cmaczo, I imagine writing such a self-promoting post might not be your favorite thing to do, but do you want to take a stab at an outline as a first step, we can discuss that, and then you can add some meat to the bones?

**Comment by cmaczo** [comment]
@mlissner I wasn't subscribed to notifications when you mentioned me here, but I will add this to my list!

**Comment by cmaczo** [comment]
Here's my proposal: Instead of "Announcing our user researcher" we talk about "Why we're starting our case management and filing project with user research" 

Outline:

* Reiterate the vision of the grant and the project: break courts free from proprietary systems that don't serve anyone's needs, and increase access to justice
* But we know lots of people are working in that space, the systems are complicated and we want to make things better, not worse...so we're starting with research!
* Briefly define user experience research, mention all our aspirational peers who take that approach, and why sometimes it's better not to "build first"
* To do that research, we hired a user researcher, this dude Colin (by the way, he's done this in other places)
* Over the next few months, we will:
  * Compile a survey of the landscape of existing products and tools in this space
  * Speak directly with court administrators, advocates, litigants and others about their experiences with a wide variety of state systems
  * Work with courts to prototype potential ideas that could help them improve case management
  * We'll do this all very openly, sign up for our newsletter, etc.
* To that end, we're seeking court partners! Get in touch with us, etc.

**Comment by mlissner** [comment]
That will make a fantastic post. No comments. Please proceed!

**Comment by cmaczo** [comment]
And here is a draft: https://docs.google.com/document/d/1dz2oix1s-IihIryP834-gWGf71Xa9tfjDV88P0qzYZI/edit#heading=h.tp34ixlg0m0y

**Comment by mlissner** [comment]
Draft looks good. I made a few little comments for you. Thank you!

**Comment by cmaczo** [comment]
I addressed your comments @mlissner and will now work on a PR for the website.
