### ISSUE TITLE
Take down PM position

### ISSUE THREAD

**Issue by mlissner** [freelawproject/free.law#209]
It should be added to the bottom like the others and the page updated as needed.

**Comment by elisa-a-v** [comment]
should the PM position be at the top of the bottom list?

and a very minor question: I know we're adding a new open position in #219 but the section will be empty in this PR, should I add some sort of text like "Check back soon" or something? probably doesn't matter since it will be populated right after but I thought it was best to ask.

**Comment by mlissner** [comment]
Doesn't really matter in the meantime. 

You can put the old posts at the top!
